//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJEMPLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_RIESGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_P_RIESGO()
        {
            this.FUWEB_POLIZA = new HashSet<FUWEB_POLIZA>();
        }
    
        public int ID_RIESGO { get; set; }
        public string S_RIESGOSACS { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_POLIZA> FUWEB_POLIZA { get; set; }
    }
}
