//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJEMPLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_POLIZA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_POLIZA()
        {
            this.FUWEB_UBICACION_GEOGRAFICA = new HashSet<FUWEB_UBICACION_GEOGRAFICA>();
        }
    
        public int NRO_POLIZA { get; set; }
        public int NRO_BIZFLOW { get; set; }
        public int ID_TIPOPOLIZA { get; set; }
        public Nullable<System.DateTime> VIGENTE_INICIO { get; set; }
        public Nullable<System.DateTime> VIGENTE_FINAL { get; set; }
        public int ID_RIESGO { get; set; }
        public string SIGLA_MONEDA { get; set; }
        public Nullable<int> ID_SUCURSAL { get; set; }
        public Nullable<int> ID_ESTADOCOBERTURA { get; set; }
        public int ID_CANALVENTA { get; set; }
        public int ID_LINEANEGOCIO { get; set; }
        public string COMENTARIO { get; set; }
        public int ID_TIPOADDITION { get; set; }
        public string NUEVONEGOCIO { get; set; }
        public string ADDITION { get; set; }
        public Nullable<int> ID_ESTADOFORMULARIO { get; set; }
        public Nullable<int> ID_ESTADOBISFLOW { get; set; }
        public int ID_FORMULARIODETALLE { get; set; }
        public Nullable<decimal> NRO_POLIZA_SACS { get; set; }
    
        public virtual FUWEB_P_CANALVENTA FUWEB_P_CANALVENTA { get; set; }
        public virtual FUWEB_P_LINEANEGOCIO FUWEB_P_LINEANEGOCIO { get; set; }
        public virtual FUWEB_P_RIESGO FUWEB_P_RIESGO { get; set; }
        public virtual FUWEB_P_TIPOADDITION FUWEB_P_TIPOADDITION { get; set; }
        public virtual FUWEB_P_TIPOPOLIZA FUWEB_P_TIPOPOLIZA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_UBICACION_GEOGRAFICA> FUWEB_UBICACION_GEOGRAFICA { get; set; }
    }
}
