//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJEMPLO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IFW_AGL_TIPOGLOSA> IFW_AGL_TIPOGLOSA { get; set; }
        public virtual DbSet<FUWEB_POLIZA> FUWEB_POLIZA { get; set; }
        public virtual DbSet<FUWEB_P_CANALVENTA> FUWEB_P_CANALVENTA { get; set; }
        public virtual DbSet<FUWEB_P_LINEANEGOCIO> FUWEB_P_LINEANEGOCIO { get; set; }
        public virtual DbSet<FUWEB_P_RIESGO> FUWEB_P_RIESGO { get; set; }
        public virtual DbSet<FUWEB_P_TIPOADDITION> FUWEB_P_TIPOADDITION { get; set; }
        public virtual DbSet<FUWEB_P_TIPOPOLIZA> FUWEB_P_TIPOPOLIZA { get; set; }
        public virtual DbSet<FUWEB_UBICACION_GEOGRAFICA> FUWEB_UBICACION_GEOGRAFICA { get; set; }
    }
}
