
namespace MS_ML_FU_DLL_DOMAIN.Domain.Constantes.BaseDatos
{
    public enum AtributoPestanaParametrica
    {
        NO_APLICA = 0,
        TIPO_POLIZA = 1,
        VIGENCIA_INICIAL = 2,
        VIGENCIA_FINAL = 3,
        RIESGO = 4,
        MONEDA = 5,
        SUCURSAL = 6,
        ESTADO_COBERTURA = 7,
        CANAL_VENTA = 8,
        LINEA_NEGOCIO = 9,
        COMENTARIO = 10,
        NUEVO_NEGOCIO = 11,
        ADDITION = 12,
        TIPO_ADDITION = 13,
        AGRUPACION_UBICACION = 14,
        LISTA_PRODUCTO_SALUD = 57,
        LISTA_PRODUCTO_VIDAAP = 58,
        FREECOVER = 59,
        CAPITAL_MAXIMO = 60,
        CUMULO = 61,
        IDVIDAAP = 62,
        LISTA_CASCADA = 63,
        FARMACIA = 64,
	    OTROS_CONVENIOS = 65,
        COBRO_PRIMA = 66,
	    ADDITION_PRIMA = 67,
	    PRIMA_PROPORCIONAL = 68,
	    EDADES_FIJAS = 69,
	    TARIFA_VIGENCIA = 70,
	    TARIFA_SALUD =71,
        TARIFA_VIDAAP = 72,
        TIPO_FACTURACION = 73,
        PERIODICIDAD = 74,
        DESTINATARIO = 75,
        CALCULO_PRIMA = 76,
        TIPO_PROCESO = 77,
        DIA_FRONTEA = 78,
        HES = 79,
        CONTRA_PAGO = 80,
        PRECOBRANZA = 81,
        AUTO_COBRANZA = 82,
        REPORTE_FACTURACION = 83,
        CONTABILIZACION = 84,
        TIPO_COBRO = 85,
        CONTRIBUTORIEDAD = 86,
        TIPO_CONTRIBUTORIEDAD = 87,
        TEXTO_CONTRIBUTORIEDAD = 88,
        CONTRATANTE = 89,
        ASEGURADO = 90,
        A_QUIEN = 91,
        TIPO_FACTURA = 92,
        RUT = 93,
        DV = 94,
        RIESGO_COBRANZA = 95
    }
}
