//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PRODUCTOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_COBERTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_P_COBERTURA()
        {
            this.FUWEB_P_COBERTURA_PRESTBASICA = new HashSet<FUWEB_P_COBERTURA_PRESTBASICA>();
            this.FUWEB_PRODUCTOLIST_SALUD = new HashSet<FUWEB_PRODUCTOLIST_SALUD>();
            this.FUWEB_PRODUCTOLIST_VIDAAP = new HashSet<FUWEB_PRODUCTOLIST_VIDAAP>();
            this.FUWEB_PRODUCTOCASCADA = new HashSet<FUWEB_PRODUCTOCASCADA>();
        }
    
        public int ID_COBERTURA { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public int NRO_SACS { get; set; }
        public int ID_TIPOPRODUCTO { get; set; }
        public Nullable<short> ORDENAR { get; set; }
    
        public virtual FUWEB_P_TIPOPRODUCTO FUWEB_P_TIPOPRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_P_COBERTURA_PRESTBASICA> FUWEB_P_COBERTURA_PRESTBASICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_PRODUCTOLIST_SALUD> FUWEB_PRODUCTOLIST_SALUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_PRODUCTOLIST_VIDAAP> FUWEB_PRODUCTOLIST_VIDAAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_PRODUCTOCASCADA> FUWEB_PRODUCTOCASCADA { get; set; }
    }
}
