//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PRODUCTOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PRODUCTOCASCADA
    {
        public int ID_CASCADA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_COBERTURA { get; set; }
        public Nullable<int> EDAD_HASTA { get; set; }
        public string SIGLA_SEXO { get; set; }
        public string SIGLA_RELACION { get; set; }
        public string CODIGO_PLAN { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string INCLUYE { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        public virtual FUWEB_P_COBERTURA FUWEB_P_COBERTURA { get; set; }
        public virtual FUWEB_P_TIPOPRODUCTO FUWEB_P_TIPOPRODUCTO { get; set; }
    }
}
