//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PRODUCTOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_PRESTACION
    {
        public int ID_PRESTACION { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public int ID_PRESTACIONGENERICA { get; set; }
        public int ID_PRESTACIONSUBGRUPO { get; set; }
        public string SIGLA_SACS { get; set; }
    
        public virtual FUWEB_P_PRESTACIONSUBGRUPO FUWEB_P_PRESTACIONSUBGRUPO { get; set; }
        public virtual FUWEB_P_PRESTACIONGENERICA FUWEB_P_PRESTACIONGENERICA { get; set; }
    }
}
