//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PRODUCTOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PRODUCTOLIST_VIDAAP
    {
        public int ID_PRODUCTOLIST_VIDAAP { get; set; }
        public int ID_COBERTURA { get; set; }
        public string CAPITAL_FIJO { get; set; }
        public Nullable<decimal> CANTIDAD_RENTA { get; set; }
        public Nullable<decimal> CAPITAL_MINIMO_PESO { get; set; }
        public Nullable<decimal> CAPITAL_MAXIMO_UF { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        public virtual FUWEB_P_COBERTURA FUWEB_P_COBERTURA { get; set; }
    }
}
