//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PRODUCTOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PRODUCTO_VIDAAP
    {
        public int ID_PRODUCTO_VIDAAP { get; set; }
        public string FREECOVER { get; set; }
        public Nullable<decimal> CAPITALMAXINO { get; set; }
        public string CUMULO { get; set; }
        public int ID_AGRUPACION { get; set; }
    }
}
