//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PRODUCTOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_P_COBERTURA> FUWEB_P_COBERTURA { get; set; }
        public virtual DbSet<FUWEB_P_PRESTACIONBASICA> FUWEB_P_PRESTACIONBASICA { get; set; }
        public virtual DbSet<FUWEB_P_PRESTACIONBASICGENERIC> FUWEB_P_PRESTACIONBASICGENERIC { get; set; }
        public virtual DbSet<FUWEB_P_PRESTACIONGENERICA> FUWEB_P_PRESTACIONGENERICA { get; set; }
        public virtual DbSet<FUWEB_P_PRESTACIONSUBGRUPO> FUWEB_P_PRESTACIONSUBGRUPO { get; set; }
        public virtual DbSet<FUWEB_P_TIPOPRODUCTO> FUWEB_P_TIPOPRODUCTO { get; set; }
        public virtual DbSet<FUWEB_P_PRESTACION> FUWEB_P_PRESTACION { get; set; }
        public virtual DbSet<FUWEB_P_COBERTURA_PRESTBASICA> FUWEB_P_COBERTURA_PRESTBASICA { get; set; }
        public virtual DbSet<FUWEB_PRODUCTOLIST_SALUD> FUWEB_PRODUCTOLIST_SALUD { get; set; }
        public virtual DbSet<FUWEB_PRODUCTOLIST_VIDAAP> FUWEB_PRODUCTOLIST_VIDAAP { get; set; }
        public virtual DbSet<FUWEB_PRODUCTO_VIDAAP> FUWEB_PRODUCTO_VIDAAP { get; set; }
        public virtual DbSet<FUWEB_PRODUCTOCASCADA> FUWEB_PRODUCTOCASCADA { get; set; }
    }
}
