//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_AGRUPACION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_AGRUPACION
    {
        public int ID_AGRUPACION { get; set; }
        public string NOMBRE_AGRUPACION { get; set; }
        public int NRO_POLIZA { get; set; }
        public Nullable<int> ID_UBICACION { get; set; }
        public Nullable<int> ID_LUGARDESPACHO { get; set; }
    }
}
