//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_IMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_IMEDTOPEMONTO
    {
        public int ID_IMEDTOPEMONTO { get; set; }
        public int ID_TIPOTOPEMONTO { get; set; }
        public int MINIMO_PESOS { get; set; }
        public int MAXIMO_UF { get; set; }
        public int ID_IMED { get; set; }
    
        public virtual FUWEB_IMED FUWEB_IMED { get; set; }
    }
}
