//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_IMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_IMEDFRECUENCIA
    {
        public int ID_FRECUENCIA { get; set; }
        public Nullable<int> ID_TIPOFRECUENCIA { get; set; }
        public int CANTIDAD { get; set; }
        public int ID_IMED { get; set; }
    
        public virtual FUWEB_IMED FUWEB_IMED { get; set; }
        public virtual FUWEB_P_TIPOFRECUENCIA FUWEB_P_TIPOFRECUENCIA { get; set; }
    }
}
