//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_IMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_PRESTADORGRUPOSACS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_P_PRESTADORGRUPOSACS()
        {
            this.FUWEB_IMEDPRESTADORESEXCEPCION = new HashSet<FUWEB_IMEDPRESTADORESEXCEPCION>();
        }
    
        public int ID_PRESTADORGRUPOSACS { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public int ID_PRESTADORGRUPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_IMEDPRESTADORESEXCEPCION> FUWEB_IMEDPRESTADORESEXCEPCION { get; set; }
        public virtual FUWEB_P_PRESTADORGRUPO FUWEB_P_PRESTADORGRUPO { get; set; }
    }
}
