//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_IMED.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_P_TIPOIMED> FUWEB_P_TIPOIMED { get; set; }
        public virtual DbSet<FUWEB_IMED> FUWEB_IMED { get; set; }
        public virtual DbSet<FUWEB_IMEDFRECUENCIA> FUWEB_IMEDFRECUENCIA { get; set; }
        public virtual DbSet<FUWEB_IMEDPRESTADORES> FUWEB_IMEDPRESTADORES { get; set; }
        public virtual DbSet<FUWEB_IMEDPRESTADORESEXCEPCION> FUWEB_IMEDPRESTADORESEXCEPCION { get; set; }
        public virtual DbSet<FUWEB_IMEDTOPEMONTO> FUWEB_IMEDTOPEMONTO { get; set; }
        public virtual DbSet<FUWEB_P_PRESTADORGRUPO> FUWEB_P_PRESTADORGRUPO { get; set; }
        public virtual DbSet<FUWEB_P_PRESTADORGRUPOSACS> FUWEB_P_PRESTADORGRUPOSACS { get; set; }
        public virtual DbSet<FUWEB_P_TIPOFRECUENCIA> FUWEB_P_TIPOFRECUENCIA { get; set; }
    }
}
