//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_ACCESO_PERFIL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_POLIZA
    {
        public int NRO_POLIZA { get; set; }
        public int NRO_BIZFLOW { get; set; }
        public int ID_TIPOPOLIZA { get; set; }
        public Nullable<System.DateTime> VIGENTE_INICIO { get; set; }
        public Nullable<System.DateTime> VIGENTE_FINAL { get; set; }
        public int ID_RIESGO { get; set; }
        public string SIGLA_MONEDA { get; set; }
        public Nullable<int> ID_SUCURSAL { get; set; }
        public Nullable<int> ID_ESTADOCOBERTURA { get; set; }
        public int ID_CANALVENTA { get; set; }
        public int ID_LINEANEGOCIO { get; set; }
        public string COMENTARIO { get; set; }
        public int ID_TIPOADDITION { get; set; }
        public string NUEVONEGOCIO { get; set; }
        public string ADDITION { get; set; }
        public Nullable<int> ID_ESTADOFORMULARIO { get; set; }
        public Nullable<int> ID_ESTADOBISFLOW { get; set; }
        public int ID_FORMULARIODETALLE { get; set; }
    
        public virtual FUWEB_P_TIPOFORMULARIODETALLE FUWEB_P_TIPOFORMULARIODETALLE { get; set; }
    }
}
