//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_ACCESO_PERFIL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_REDIRECCION
    {
        public int ID_REDIRECCION { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public string EXISTEBIZFOR { get; set; }
    }
}
