//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_ACCESO_PERFIL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_ESTADOFORMULARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_P_ESTADOFORMULARIO()
        {
            this.FUWEB_PERMISOAREA = new HashSet<FUWEB_PERMISOAREA>();
        }
    
        public int ID_ESTADOFORMULARIO { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_PERMISOAREA> FUWEB_PERMISOAREA { get; set; }
    }
}
