//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_ACCESO_PERFIL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PERMISOESTADO
    {
        public int ID_PERMISOAESTADO { get; set; }
        public Nullable<int> ID_AREA { get; set; }
        public Nullable<int> ID_TIPOFORMULARIO { get; set; }
        public Nullable<int> ID_ESTADOBISFLOW { get; set; }
    
        public virtual FUWEB_P_AREA FUWEB_P_AREA { get; set; }
        public virtual FUWEB_P_ESTADOBIZFLOW FUWEB_P_ESTADOBIZFLOW { get; set; }
        public virtual FUWEB_P_TIPOFORMULARIO FUWEB_P_TIPOFORMULARIO { get; set; }
    }
}
