//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_ACCESO_PERFIL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string SIGLA_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public int ID_AREA { get; set; }
        public string CORREO { get; set; }
    
        public virtual FUWEB_P_AREA FUWEB_P_AREA { get; set; }
    }
}
