//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_ACCESO_PERFIL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PERMISOAREA
    {
        public int ID_PERMISOAREA { get; set; }
        public int ID_TIPOPERMISO { get; set; }
        public int ID_AREA { get; set; }
        public int ID_PESTANA { get; set; }
        public int ID_ESTADOFORMULARIO { get; set; }
    
        public virtual FUWEB_P_AREA FUWEB_P_AREA { get; set; }
        public virtual FUWEB_P_ESTADOFORMULARIO FUWEB_P_ESTADOFORMULARIO { get; set; }
        public virtual FUWEB_P_PESTANA FUWEB_P_PESTANA { get; set; }
        public virtual FUWEB_P_TIPOPERMISO FUWEB_P_TIPOPERMISO { get; set; }
    }
}
