//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_ACCESO_PERFIL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_P_AREA> FUWEB_P_AREA { get; set; }
        public virtual DbSet<FUWEB_P_ESTADOBIZFLOW> FUWEB_P_ESTADOBIZFLOW { get; set; }
        public virtual DbSet<FUWEB_P_ESTADOFORMULARIO> FUWEB_P_ESTADOFORMULARIO { get; set; }
        public virtual DbSet<FUWEB_P_PESTANA> FUWEB_P_PESTANA { get; set; }
        public virtual DbSet<FUWEB_P_TIPOFORMULARIO> FUWEB_P_TIPOFORMULARIO { get; set; }
        public virtual DbSet<FUWEB_P_TIPOFORMULARIODETALLE> FUWEB_P_TIPOFORMULARIODETALLE { get; set; }
        public virtual DbSet<FUWEB_P_TIPOPERMISO> FUWEB_P_TIPOPERMISO { get; set; }
        public virtual DbSet<FUWEB_PERMISOAREA> FUWEB_PERMISOAREA { get; set; }
        public virtual DbSet<FUWEB_PERMISOESTADO> FUWEB_PERMISOESTADO { get; set; }
        public virtual DbSet<FUWEB_REDIRECCION> FUWEB_REDIRECCION { get; set; }
        public virtual DbSet<FUWEB_USUARIO> FUWEB_USUARIO { get; set; }
        public virtual DbSet<FUWEB_POLIZA> FUWEB_POLIZA { get; set; }
    }
}
