//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_BMI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_GRUPOISAPRE
    {
        public int ID_P_GRUPOISAPRE { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public int NRO_SAC { get; set; }
    }
}
