//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_COBRANZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_COBRANZAGRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_COBRANZAGRUPO()
        {
            this.FUWEB_COBRANZARIESGO = new HashSet<FUWEB_COBRANZARIESGO>();
        }
    
        public int ID_COBRANZAGRUPO { get; set; }
        public string CONTRIBUTORIEDAD { get; set; }
        public Nullable<int> ID_CONTRIBUTORIEDAD { get; set; }
        public Nullable<int> PORCENTAJECONTRATANTE { get; set; }
        public Nullable<int> PORCENTAJEASEGURADO { get; set; }
        public string ESPECIALCONTRIBUTORIEDAD { get; set; }
        public Nullable<int> ID_AQUIENCOBRANZA { get; set; }
        public string SIGLA_TIPOFACTURA { get; set; }
        public Nullable<int> RUT_FACTURACION { get; set; }
        public string DV_FACTURACION { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        public virtual FUWEB_P_AQUIENCOBRANZA FUWEB_P_AQUIENCOBRANZA { get; set; }
        public virtual FUWEB_P_CONTRIBUTORIEDAD FUWEB_P_CONTRIBUTORIEDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_COBRANZARIESGO> FUWEB_COBRANZARIESGO { get; set; }
    }
}
