//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_COBRANZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_COBRANZARIESGO
    {
        public int ID_TIPORIESGO { get; set; }
        public int ID_COBRANZAGRUPO { get; set; }
        public string TEXTO { get; set; }
    
        public virtual FUWEB_COBRANZAGRUPO FUWEB_COBRANZAGRUPO { get; set; }
        public virtual FUWEB_P_RIESGOFACTURACION FUWEB_P_RIESGOFACTURACION { get; set; }
    }
}
