//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_COBRANZA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_P_AQUIENCOBRANZA> FUWEB_P_AQUIENCOBRANZA { get; set; }
        public virtual DbSet<FUWEB_P_CALCULOPRIMA> FUWEB_P_CALCULOPRIMA { get; set; }
        public virtual DbSet<FUWEB_P_DESTINATARIOCOBRANZA> FUWEB_P_DESTINATARIOCOBRANZA { get; set; }
        public virtual DbSet<FUWEB_P_RIESGOFACTURACION> FUWEB_P_RIESGOFACTURACION { get; set; }
        public virtual DbSet<FUWEB_P_TIPOCOBRO> FUWEB_P_TIPOCOBRO { get; set; }
        public virtual DbSet<FUWEB_P_TIPOFACTURACIONCOBR> FUWEB_P_TIPOFACTURACIONCOBR { get; set; }
        public virtual DbSet<FUWEB_COBRANZA> FUWEB_COBRANZA { get; set; }
        public virtual DbSet<FUWEB_P_CONTRIBUTORIEDAD> FUWEB_P_CONTRIBUTORIEDAD { get; set; }
        public virtual DbSet<FUWEB_COBRANZAGRUPO> FUWEB_COBRANZAGRUPO { get; set; }
        public virtual DbSet<FUWEB_COBRANZARIESGO> FUWEB_COBRANZARIESGO { get; set; }
    }
}
