//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_BROKER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_BROKERCORREDOR
    {
        public int ID_CORREDOR { get; set; }
        public int RUT_CORREDOR { get; set; }
        public string DV_CORREDOR { get; set; }
        public string NOMBRE_CORREDOR { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string GIRO { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string COMUNA { get; set; }
        public string POLIZA_GARANTIA_VIGENTE { get; set; }
        public string NOMBRE_CONTACTO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> FORMA_PAGO { get; set; }
        public Nullable<int> TIPO_CUENTA { get; set; }
        public Nullable<int> NRO_CUENTA { get; set; }
        public Nullable<int> BANCO { get; set; }
        public int ID_HOLDING { get; set; }
        public string ID_ADMINISTRADOR { get; set; }
        public string ID_EJECUTIVO_COBRANZA { get; set; }
        public string ID_EJECUTIVO_COMERCIAL { get; set; }
        public string ID_EJECUTIVO_MOVIMIENTO { get; set; }
        public int ID_AGRUPACION { get; set; }
    }
}
