//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_BROKER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_BROKERCCTE
    {
        public int ID_CCTE { get; set; }
        public int RUTCCTE { get; set; }
        public string DVCCTE { get; set; }
        public string NOMBRECCTE { get; set; }
        public string GRUPOEMPRESAS { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string COMUNA { get; set; }
        public string CIUDAD { get; set; }
        public string GIRO { get; set; }
        public string NOMBRE_CONTACTO { get; set; }
        public string EMAIL { get; set; }
        public string NOMBRE_MANDANTE { get; set; }
        public string RUT_MANDANTE { get; set; }
        public int ID_TIPOCCTE { get; set; }
        public int ID_AGRUPACION { get; set; }
    }
}
