//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_MENSAJE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_MENSAJES
    {
        public int ID_MENSAJE { get; set; }
        public int ID_ATRIBUTOPESTANA { get; set; }
        public int ID_AGRUPACION { get; set; }
        public int ID_ESTADOATRIBUTO { get; set; }
        public string MENSAJE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string SIGLA_USUARIO { get; set; }
    
        public virtual FUWEB_P_ATRIBUTOPESTANA FUWEB_P_ATRIBUTOPESTANA { get; set; }
        public virtual FUWEB_P_ESTADOATRIBUTO FUWEB_P_ESTADOATRIBUTO { get; set; }
    }
}
