//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PLANGRILLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PLANGRILLA_VIDAAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_PLANGRILLA_VIDAAP()
        {
            this.FUWEB_PLANGRILLA_OBSERVIDAAP = new HashSet<FUWEB_PLANGRILLA_OBSERVIDAAP>();
        }
    
        public int ID_PLANGRILLA_VIDAAP { get; set; }
        public string ID_PLAN { get; set; }
        public int ID_COBERTURA { get; set; }
        public int INDEMNIZAION { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_PLANGRILLA_OBSERVIDAAP> FUWEB_PLANGRILLA_OBSERVIDAAP { get; set; }
    }
}
