//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PLANGRILLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PLANGRILLA_OBSERVIDAAP
    {
        public int ID_OBSERVIDAAP { get; set; }
        public string OBSERVACION { get; set; }
        public int ID_PLANGRILLA_VIDAAP { get; set; }
    
        public virtual FUWEB_PLANGRILLA_VIDAAP FUWEB_PLANGRILLA_VIDAAP { get; set; }
    }
}
