//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PLANGRILLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PLANGRILLA_PRESTBASICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_PLANGRILLA_PRESTBASICA()
        {
            this.FUWEB_PLANGRILLA_PREFERENTE = new HashSet<FUWEB_PLANGRILLA_PREFERENTE>();
            this.FUWEB_PLANGRILLA_PRESTACIONES = new HashSet<FUWEB_PLANGRILLA_PRESTACIONES>();
        }
    
        public int ID_PLANGRILLA_PRESTBASICA { get; set; }
        public string DESCRIPCION_PLAN { get; set; }
        public string CODIGOPLAN { get; set; }
        public string NOMBRE_NUEVAAGRUPACION { get; set; }
        public int ID_PRESTACIONBASICA { get; set; }
        public int ID_JERARQUIA_PRESTBASICA { get; set; }
        public int ID_COBERTURA { get; set; }
        public Nullable<int> SCFMONTO { get; set; }
        public Nullable<int> CARENCIA_DIA { get; set; }
        public Nullable<int> REEMBOLSO_DIRECTO { get; set; }
        public Nullable<int> REEMBOLSO_BONO { get; set; }
        public Nullable<int> REEMBOLSO_ISAPRE { get; set; }
        public Nullable<int> TOPE { get; set; }
        public Nullable<int> ID_NIVELTOPE { get; set; }
        public Nullable<int> LIMITE { get; set; }
        public Nullable<int> ID_NIVELLIMITE { get; set; }
        public string EXCEDENTE { get; set; }
        public string SIN_DEDUCIBLE { get; set; }
        public string SCF { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_PLANGRILLA_PREFERENTE> FUWEB_PLANGRILLA_PREFERENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_PLANGRILLA_PRESTACIONES> FUWEB_PLANGRILLA_PRESTACIONES { get; set; }
    }
}
