//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PLANGRILLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_PLANGRILLA_PREFERENTE
    {
        public int ID_PLANGRILLA_PREFERENTE { get; set; }
        public Nullable<int> ID_CLINICA_PREFEREN { get; set; }
        public Nullable<int> PORCENTAJE_PREFEREN { get; set; }
        public Nullable<int> ID_TIPOPREVISIONSALUD { get; set; }
        public int ID_PLANGRILLA_PRESTBASICA { get; set; }
    
        public virtual FUWEB_PLANGRILLA_PRESTBASICA FUWEB_PLANGRILLA_PRESTBASICA { get; set; }
    }
}
