//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_PLANGRILLA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_P_PRESTADORGRUPO> FUWEB_P_PRESTADORGRUPO { get; set; }
        public virtual DbSet<FUWEB_PLANGRILLA_OBSERSALUD> FUWEB_PLANGRILLA_OBSERSALUD { get; set; }
        public virtual DbSet<FUWEB_PLANGRILLA_OBSERVIDAAP> FUWEB_PLANGRILLA_OBSERVIDAAP { get; set; }
        public virtual DbSet<FUWEB_PLANGRILLA_PREFERENTE> FUWEB_PLANGRILLA_PREFERENTE { get; set; }
        public virtual DbSet<FUWEB_PLANGRILLA_PRESTACIONES> FUWEB_PLANGRILLA_PRESTACIONES { get; set; }
        public virtual DbSet<FUWEB_PLANGRILLA_PRESTBASICA> FUWEB_PLANGRILLA_PRESTBASICA { get; set; }
        public virtual DbSet<FUWEB_PLANGRILLA_VIDAAP> FUWEB_PLANGRILLA_VIDAAP { get; set; }
    }
}
