//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_TARIFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_TARIFAGRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_TARIFAGRUPO()
        {
            this.FUWEB_TARIFAGRUPOLISTAPRIMA = new HashSet<FUWEB_TARIFAGRUPOLISTAPRIMA>();
            this.FUWEB_TARIFAGRUPOLISTAESPECIAL = new HashSet<FUWEB_TARIFAGRUPOLISTAESPECIAL>();
        }
    
        public int ID_TARIFAGRUPO { get; set; }
        public int ID_COBERTURA { get; set; }
        public int ID_TIPOPRODUCTO { get; set; }
        public int ID_DEFINICIONTRIBUTARIA { get; set; }
        public string GRUPOFAMILIAR { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        public virtual FUWEB_P_DEFINICIONTRIBUTARIA FUWEB_P_DEFINICIONTRIBUTARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_TARIFAGRUPOLISTAPRIMA> FUWEB_TARIFAGRUPOLISTAPRIMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_TARIFAGRUPOLISTAESPECIAL> FUWEB_TARIFAGRUPOLISTAESPECIAL { get; set; }
    }
}
