//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_TARIFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_TARIFA
    {
        public int ID_TARIFA { get; set; }
        public string SIGLA_COBRO { get; set; }
        public string ADICION_TARIFA { get; set; }
        public string TARIFA_VIGENCIA { get; set; }
        public string PRIMA_PROPORCIONAL { get; set; }
        public string EDAD_FIJA { get; set; }
        public int NRO_POLIZA { get; set; }
    }
}
