//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_TARIFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_DEFINICIONTRIBUTARIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_P_DEFINICIONTRIBUTARIA()
        {
            this.FUWEB_TARIFAGRUPO = new HashSet<FUWEB_TARIFAGRUPO>();
        }
    
        public int ID_DEFINICIONTRIBUTARIA { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public int NRO_SAC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_TARIFAGRUPO> FUWEB_TARIFAGRUPO { get; set; }
    }
}
