//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_TARIFA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_P_DEFINICIONTRIBUTARIA> FUWEB_P_DEFINICIONTRIBUTARIA { get; set; }
        public virtual DbSet<FUWEB_TARIFA> FUWEB_TARIFA { get; set; }
        public virtual DbSet<FUWEB_TARIFAGRUPO> FUWEB_TARIFAGRUPO { get; set; }
        public virtual DbSet<FUWEB_TARIFAGRUPOLISTAESPECIAL> FUWEB_TARIFAGRUPOLISTAESPECIAL { get; set; }
        public virtual DbSet<FUWEB_TARIFAGRUPOLISTAPRIMA> FUWEB_TARIFAGRUPOLISTAPRIMA { get; set; }
    }
}
