//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_DATOSPOLIZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_UBICACION_GEOGRAFICA
    {
        public int ID_UBICACIONGEOGRAFICA { get; set; }
        public string NOMBRE_UBICACIONGEOGRAFICA { get; set; }
        public int NRO_POLIZA { get; set; }
    
        public virtual FUWEB_POLIZA FUWEB_POLIZA { get; set; }
    }
}
