//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_MENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_P_TIPOFORMULARIODETALLE
    {
        public int ID_TIPOFORMUALRIODETALLE { get; set; }
        public string NOMBRE { get; set; }
        public string VIGENTE { get; set; }
        public int ID_TIPOFORMULARIO { get; set; }
    
        public virtual FUWEB_P_TIPOFORMULARIO FUWEB_P_TIPOFORMULARIO { get; set; }
    }
}
