//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_CONVENIOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_CONVENIOOTROS
    {
        public int ID_OTROSCONVENIOS { get; set; }
        public int ID_CONVENIO { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        public virtual FUWEB_P_CONVENIO FUWEB_P_CONVENIO { get; set; }
    }
}
