//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_CONVENIOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_CONVENIOFARMACIA
    {
        public int ID_LISTAFARMACIA { get; set; }
        public int ID_FARMACIA { get; set; }
        public int ID_VADEMECUM { get; set; }
        public int ID_TIPOFACTURACION { get; set; }
        public string FRANQUICIA { get; set; }
        public string SIGLAMONEDA { get; set; }
        public Nullable<decimal> MONTOASEGURADO { get; set; }
        public string OPS { get; set; }
        public string MODOOPERACION { get; set; }
        public int ID_AGRUPACION { get; set; }
    
        public virtual FUWEB_P_CONVENIO FUWEB_P_CONVENIO { get; set; }
        public virtual FUWEB_P_TIPOFACTURACION FUWEB_P_TIPOFACTURACION { get; set; }
        public virtual FUWEB_P_VADEMECUM FUWEB_P_VADEMECUM { get; set; }
    }
}
