//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_CONVENIOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_CONVENIOOTROS> FUWEB_CONVENIOOTROS { get; set; }
        public virtual DbSet<FUWEB_P_TIPOCONVENIO> FUWEB_P_TIPOCONVENIO { get; set; }
        public virtual DbSet<FUWEB_P_TIPOFACTURACION> FUWEB_P_TIPOFACTURACION { get; set; }
        public virtual DbSet<FUWEB_P_VADEMECUM> FUWEB_P_VADEMECUM { get; set; }
        public virtual DbSet<FUWEB_P_CONVENIO> FUWEB_P_CONVENIO { get; set; }
        public virtual DbSet<FUWEB_CONVENIOFARMACIA> FUWEB_CONVENIOFARMACIA { get; set; }
    }
}
