//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_CREDENCIALES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDENCIAL
    {
        public string Usuario { get; set; }
        public Nullable<decimal> NroBizflow { get; set; }
        public Nullable<decimal> ModoAcceso { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public string TokenAcceso { get; set; }
        public string TokenRefresco { get; set; }
        public Nullable<decimal> TiempoExpiracionAcceso { get; set; }
        public Nullable<decimal> TiempoExpiracionRefresco { get; set; }
    }
}
