//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_CONDICIONES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_CONDESP_TEXTO
    {
        public int ID_CONDESP_TEXTO { get; set; }
        public int ID_TIPOOBSERVACION { get; set; }
        public string TEXTO { get; set; }
        public int ID_AGRUPACION { get; set; }
    }
}
