//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_CONDICIONES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_CONDESP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUWEB_CONDESP()
        {
            this.FUWEB_CONDESP_GRUPO_DP = new HashSet<FUWEB_CONDESP_GRUPO_DP>();
            this.FUWEB_CONDESP_COBERTU_DP = new HashSet<FUWEB_CONDESP_COBERTU_DP>();
        }
    
        public int ID_CONDESP { get; set; }
        public string FLD { get; set; }
        public string DP { get; set; }
        public string DP_HOLDING { get; set; }
        public string DP_PLIZA { get; set; }
        public Nullable<int> MONTO_FONTO { get; set; }
        public string NOMBRE_FONDO { get; set; }
        public Nullable<int> NRO_FONDO { get; set; }
        public Nullable<int> VERSION { get; set; }
        public int NRO_POLIZA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_CONDESP_GRUPO_DP> FUWEB_CONDESP_GRUPO_DP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUWEB_CONDESP_COBERTU_DP> FUWEB_CONDESP_COBERTU_DP { get; set; }
    }
}
