//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_CONDICIONES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUWEB_CONDESP_GRUPO_DP
    {
        public int ID_GRUPO_DP { get; set; }
        public int ID_AGRUPACION { get; set; }
        public int ID_CONDESP { get; set; }
    
        public virtual FUWEB_CONDESP FUWEB_CONDESP { get; set; }
    }
}
