//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_ML_FU_P_CONDICIONES.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUWEB_CONDESP> FUWEB_CONDESP { get; set; }
        public virtual DbSet<FUWEB_CONDESP_COBERTU_DP> FUWEB_CONDESP_COBERTU_DP { get; set; }
        public virtual DbSet<FUWEB_CONDESP_GRUPO_DP> FUWEB_CONDESP_GRUPO_DP { get; set; }
        public virtual DbSet<FUWEB_CONDESP_TEXTO> FUWEB_CONDESP_TEXTO { get; set; }
    }
}
